#pragma once

namespace Core::HLE {
enum CustomNID {
    CUSTOM_NID_IDLE = 0x1000,
    CUSTOM_NID_RETURN_FROM_THREAD = 0x1001,
    CUSTOM_NID_RETURN_FROM_CALLBACK = 0x1002,
    CUSTOM_NID_RETURN_FROM_INTERRUPT = 0x1003,
    CUSTOM_NID_ASIO = 0x1004,
};
}